version: '3.8'

services:
  # Server service
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "3000:3000"
    env_file: ./.env # Include environment file if used
    environment:
      - MONGO_URI=${MONGO_URI} # Optional environment variable for MongoDB connection
    depends_on:
      - mongodb
    restart: always

  # Client service
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "5173:3001" # Adjust port if necessary
    volumes:
      - ./client/build:/app/build # Mount local build directory into container
    depends_on:
      - server
    restart: always

  # Database service
  mongodb:
    image: mongo:latest
    container_name: mongodb_server
    env_file: ./.env # Include environment file if used
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mydata:/data/db
    restart: always

# Volumes define
volumes:
  mydata:
